"""split_business_impact

Revision ID: 0f4a8642adb4
Revises: 94a4641384d9
Create Date: 2026-06-28 15:30:43.633458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4a8642adb4'
down_revision = '94a4641384d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riesgos', sa.Column('business_impact_operational', sa.Text(), nullable=True))
    op.add_column('riesgos', sa.Column('business_impact_financial', sa.Text(), nullable=True))
    op.add_column('riesgos', sa.Column('business_impact_normative', sa.Text(), nullable=True))
    op.add_column('riesgos', sa.Column('business_impact_reputational', sa.Text(), nullable=True))
    op.drop_column('riesgos', 'business_impact_desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riesgos', sa.Column('business_impact_desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('riesgos', 'business_impact_reputational')
    op.drop_column('riesgos', 'business_impact_normative')
    op.drop_column('riesgos', 'business_impact_financial')
    op.drop_column('riesgos', 'business_impact_operational')
    # ### end Alembic commands ###
