"""Add ip_address to Asset

Revision ID: 2762c7f09112
Revises: 0009_restructure
Create Date: 2026-06-24 18:42:31.998850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2762c7f09112'
down_revision = '0009_restructure'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_cuestionario')
    op.drop_table('cuestionarios')
    op.add_column('assets', sa.Column('ip_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'ip_address')
    op.create_table('cuestionarios',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('definition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['questionnaire_definitions.id'], name='cuestionarios_definition_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='cuestionarios_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cuestionarios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('respuestas_cuestionario',
    sa.Column('questionnaire_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('block', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['cuestionarios.id'], name='respuestas_cuestionario_questionnaire_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='respuestas_cuestionario_pkey'),
    sa.UniqueConstraint('questionnaire_id', 'question_id', name='uq_respuestas_cuestionario_question')
    )
    # ### end Alembic commands ###
