"""add category to scanners

Revision ID: 94a4641384d9
Revises: 2762c7f09112
Create Date: 2026-06-24 20:53:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a4641384d9'
down_revision: Union[str, None] = '2762c7f09112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanner_engines', sa.Column('category', sa.String(length=50), server_default='sast', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scanner_engines', 'category')
    # ### end Alembic commands ###
